In [45]:
import pandas as pd
from pandas import DataFrame
import numpy
df = pd.read_csv("temp.csv")
df

,Unnamed: 0,index,result,table,_field,_value,_time,derivative
0,0,0,_result,0,HT_FY_2180.PV,11.366207,2022-11-17 15:08:00+00:00,0.0
1,50,50,_result,5,HT_VI_2187A.PV,11.260000,2022-11-17 15:08:00+00:00,0.0
2,70,70,_result,7,HT_VI_2188A.PV,3.440000,2022-11-17 15:08:00+00:00,0.0
3,80,80,_result,8,HT_VI_2188B.PV,5.880833,2022-11-17 15:08:00+00:00,0.0
4,40,40,_result,4,HT_VI_2184B.PV,5.497778,2022-11-17 15:08:00+00:00,0.0
...,...,...,...,...,...,...,...,...
125,79,79,_result,7,HT_VI_2188A.PV,3.257500,2022-11-17 15:16:29.492961+00:00,0.0
126,49,49,_result,4,HT_VI_2184B.PV,5.396667,2022-11-17 15:16:29.492961+00:00,0.0
127,69,69,_result,6,HT_VI_2187B.PV,12.118333,2022-11-17 15:16:29.492961+00:00,0.0
128,9,9,_result,0,HT_FY_2180.PV,11.228750,2022-11-17 15:16:29.492961+00:00,0.0
129,129,129,_result,12,HT_ZI_2181B.PV,-0.144876,2022-11-17 15:16:29.492961+00:00,0.0

In [46]:
df["sign"] = numpy.sign(df['derivative'])

In [47]:
df["group"] = None

In [28]:
cols = df.columns.tolist()
cols.index("derivative")

7

In [48]:
def transition(info, target):
    if info["state"] == target:
        pass
    else:
        if info["state"] == 'normal':
            info["cnt"] = info["cnt"] + 1
        info["state"] = target
_info = dict(state = "normal", cnt = 0)
for rowIdx, row in df.iterrows():
    if abs(row[cols.index("derivative")]) < 0.1:
        transition(_info, "normal")
        df.at[rowIdx, 'sign'] = 0
    elif row[cols.index("derivative")] > 0:
        transition(_info, 'increasing')
        df.at[rowIdx, 'group'] = _info["cnt"]
    elif row[cols.index("derivative")] < 0:
        transition(_info, 'decreasing')
        df.at[rowIdx, 'group'] = _info["cnt"]
df = df[df.group > 0] 
for _, row in df.iterrows():
    print(row.tolist())

[102, 102, '_result', 10, 'HT_ZI_2180B.PV', -0.1183128538461538, '2022-11-17 15:10:00+00:00', 1.8992942475633847, 1.0, 1]
[112, 112, '_result', 11, 'HT_ZI_2181A.PV', -0.1602286846153846, '2022-11-17 15:10:00+00:00', 0.6991071866653016, 1.0, 1]
[72, 72, '_result', 7, 'HT_VI_2188A.PV', 3.39, '2022-11-17 15:10:00+00:00', 1.4126528943386445, 1.0, 1]
[82, 82, '_result', 8, 'HT_VI_2188B.PV', 5.959999999999999, '2022-11-17 15:10:00+00:00', 1.7485244674289708, 1.0, 1]
[2, 2, '_result', 0, 'HT_FY_2180.PV', 11.015333333333333, '2022-11-17 15:10:00+00:00', 1.4428503837759332, 1.0, 1]
[42, 42, '_result', 4, 'HT_VI_2184B.PV', 5.477777777777778, '2022-11-17 15:10:00+00:00', 0.7652300995258268, 1.0, 2]
[52, 52, '_result', 5, 'HT_VI_2187A.PV', 11.588125000000002, '2022-11-17 15:10:00+00:00', 0.907021907956413, 1.0, 2]
[122, 122, '_result', 12, 'HT_ZI_2181B.PV', -0.1454892933333333, '2022-11-17 15:10:00+00:00', 1.77028591527847, 1.0, 2]
[92, 92, '_result', 9, 'HT_ZI_2180A.PV', -0.1317045538461538, '2022-11-17 15:10:00+00:00', 1.8878332869773105, 1.0, 2]
[62, 62, '_result', 6, 'HT_VI_2187B.PV', 12.887058823529411, '2022-11-17 15:10:00+00:00', 0.4544376084921806, 1.0, 2]
[22, 22, '_result', 2, 'HT_VI_2183B.PV', 13.462352941176473, '2022-11-17 15:10:00+00:00', 0.3199448118621988, 1.0, 2]
[32, 32, '_result', 3, 'HT_VI_2184A.PV', 5.009230769230769, '2022-11-17 15:10:00+00:00', 0.829009344745723, 1.0, 2]
[53, 53, '_result', 5, 'HT_VI_2187A.PV', 10.42470588235294, '2022-11-17 15:11:00+00:00', 0.907021907956413, 1.0, 2]
[113, 113, '_result', 11, 'HT_ZI_2181A.PV', -0.1599282583333333, '2022-11-17 15:11:00+00:00', 0.6991071866653016, 1.0, 3]
[63, 63, '_result', 6, 'HT_VI_2187B.PV', 11.016470588235292, '2022-11-17 15:11:00+00:00', 0.4544376084921806, 1.0, 3]
[73, 73, '_result', 7, 'HT_VI_2188A.PV', 3.304444444444444, '2022-11-17 15:11:00+00:00', 1.4126528943386445, 1.0, 3]
[93, 93, '_result', 9, 'HT_ZI_2180A.PV', -0.13189556875, '2022-11-17 15:11:00+00:00', 1.8878332869773105, 1.0, 3]
[43, 43, '_result', 4, 'HT_VI_2184B.PV', 5.449999999999998, '2022-11-17 15:11:00+00:00', 0.7652300995258268, 1.0, 3]
[23, 23, '_result', 2, 'HT_VI_2183B.PV', 10.972941176470588, '2022-11-17 15:11:00+00:00', 0.3199448118621988, 1.0, 3]
[83, 83, '_result', 8, 'HT_VI_2188B.PV', 6.012727272727273, '2022-11-17 15:11:00+00:00', 1.7485244674289708, 1.0, 3]
[123, 123, '_result', 12, 'HT_ZI_2181B.PV', -0.1453283642857143, '2022-11-17 15:11:00+00:00', 1.77028591527847, 1.0, 3]
[33, 33, '_result', 3, 'HT_VI_2184A.PV', 5.047142857142858, '2022-11-17 15:11:00+00:00', 0.829009344745723, 1.0, 3]
[103, 103, '_result', 10, 'HT_ZI_2180B.PV', -0.1185624866666666, '2022-11-17 15:11:00+00:00', 1.8992942475633847, 1.0, 3]
[3, 3, '_result', 0, 'HT_FY_2180.PV', 11.455000000000002, '2022-11-17 15:11:00+00:00', 1.4428503837759332, 1.0, 3]
[106, 106, '_result', 10, 'HT_ZI_2180B.PV', -0.118777025, '2022-11-17 15:14:00+00:00', -1.88670966732518, -1.0, 4]
[6, 6, '_result', 0, 'HT_FY_2180.PV', 11.517666666666669, '2022-11-17 15:14:00+00:00', -1.0332459701093482, -1.0, 4]
[116, 116, '_result', 11, 'HT_ZI_2181A.PV', -0.1593511642857143, '2022-11-17 15:14:00+00:00', -1.1527564561887689, -1.0, 5]
[86, 86, '_result', 8, 'HT_VI_2188B.PV', 6.081818181818182, '2022-11-17 15:14:00+00:00', -0.3128003253176585, -1.0, 5]
[46, 46, '_result', 4, 'HT_VI_2184B.PV', 5.376153846153847, '2022-11-17 15:14:00+00:00', -0.3379146581593768, -1.0, 5]
[36, 36, '_result', 3, 'HT_VI_2184A.PV', 5.05875, '2022-11-17 15:14:00+00:00', -0.5821288195801775, -1.0, 5]
[66, 66, '_result', 6, 'HT_VI_2187B.PV', 11.40875, '2022-11-17 15:14:00+00:00', -1.0133727388538374, -1.0, 5]
[16, 16, '_result', 1, 'HT_VI_2183A.PV', 9.123529411764704, '2022-11-17 15:14:00+00:00', -1.930292712409473, -1.0, 5]
[126, 126, '_result', 12, 'HT_ZI_2181B.PV', -0.14490598, '2022-11-17 15:14:00+00:00', -1.1595052935795844, -1.0, 5]
[96, 96, '_result', 9, 'HT_ZI_2180A.PV', -0.1321828411764706, '2022-11-17 15:14:00+00:00', -1.6853520822416217, -1.0, 5]
[76, 76, '_result', 7, 'HT_VI_2188A.PV', 3.267777777777778, '2022-11-17 15:14:00+00:00', -1.1725507468319738, -1.0, 5]
[26, 26, '_result', 2, 'HT_VI_2183B.PV', 11.515, '2022-11-17 15:14:00+00:00', -0.5774296715198504, -1.0, 5]
[7, 7, '_result', 0, 'HT_FY_2180.PV', 11.671666666666669, '2022-11-17 15:15:00+00:00', -1.0332459701093482, -1.0, 5]
[17, 17, '_result', 1, 'HT_VI_2183A.PV', 9.765, '2022-11-17 15:15:00+00:00', -1.930292712409473, -1.0, 5]
[107, 107, '_result', 10, 'HT_ZI_2180B.PV', -0.1189513599999999, '2022-11-17 15:15:00+00:00', -1.88670966732518, -1.0, 5]
[97, 97, '_result', 9, 'HT_ZI_2180A.PV', -0.13235442, '2022-11-17 15:15:00+00:00', -1.6853520822416217, -1.0, 5]
[27, 27, '_result', 2, 'HT_VI_2183B.PV', 13.4775, '2022-11-17 15:15:00+00:00', -0.5774296715198504, -1.0, 5]
[117, 117, '_result', 11, 'HT_ZI_2181A.PV', -0.1591160454545454, '2022-11-17 15:15:00+00:00', -1.1527564561887689, -1.0, 5]
[87, 87, '_result', 8, 'HT_VI_2188B.PV', 6.096153846153846, '2022-11-17 15:15:00+00:00', -0.3128003253176585, -1.0, 6]
[37, 37, '_result', 3, 'HT_VI_2184A.PV', 5.036428571428572, '2022-11-17 15:15:00+00:00', -0.5821288195801775, -1.0, 6]
[67, 67, '_result', 6, 'HT_VI_2187B.PV', 12.48125, '2022-11-17 15:15:00+00:00', -1.0133727388538374, -1.0, 6]
[77, 77, '_result', 7, 'HT_VI_2188A.PV', 3.2681818181818176, '2022-11-17 15:15:00+00:00', -1.1725507468319738, -1.0, 6]
[47, 47, '_result', 4, 'HT_VI_2184B.PV', 5.403, '2022-11-17 15:15:00+00:00', -0.3379146581593768, -1.0, 6]
[127, 127, '_result', 12, 'HT_ZI_2181B.PV', -0.1447105714285714, '2022-11-17 15:15:00+00:00', -1.1595052935795844, -1.0, 6]

In [ ]:
df1[df1 > 0]

In [3]:
float("_")

ValueError: could not convert string to float: '_'